FROM node:lts-alpine AS build
WORKDIR /app

COPY web/package.json web/yarn.lock ./
RUN yarn

ARG UMAMI_URL
ENV REACT_APP_UMAMI_URL $UMAMI_URL

COPY web ./
RUN yarn build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY web/nginx.conf /etc/nginx/conf.d/default.conf
